import i18next from 'i18next';

let lang = {
  en: {
    'lang_zh':'中',
    'lang_en':'EN',
    'lang_cn':'简',
    'test_inc_tab': 'Tokens',
    'test_game_tab': 'Game',
    'test_payout_tab': 'Payout',
    'test_wallet_not_available': 'Wallet not available',
    'test_price_label': 'Buy INC at',
    'test_balance_label': 'You have',
    'test_balance': '{{balance}} INC',
    'test_register': 'Register',
    'test_end': 'Ends in',
    'test_get_buy_price': 'Quote Buy',
    'test_buy': 'Buy',
    'test_sell': 'Sell',
    'test_pot': 'Pot',
    'test_restart': 'Restart game',
    'test_pot_size': '{{pot}} INC',
    'test_price': '{{buy}} ETH/{{sell}} ETH',
    'test_get_pot': 'Query Pot Size',
    'test_bid': 'Bid',
    'test_ended': 'Game Ended?',
    'test_win': 'Payout',
    'test_get_sell_price': 'Quote Sell',
    'test_approve': 'Approve',
    'test_get_end_time': 'Query end time',
    'test_get_balance': 'View INC Balance',

    'head_register': 'Register',
    'head_not_started': 'Not started',
    'head_balance': '{{balance}} INC',
    'head_price': '{{price}} ETH',
    'head_game_ended':'Time up',
    'head_referrals':'{{referrals}} friends',
    'head_bonus':'{{bonus}} BONUS',
    'icon_eth': 'ETH',
    'icon_inc': 'INC',
    'icon_time': 'Remaining Time',
    'icon_referrals':'Friends',
    'icon_bonus':'Bonus',
    'icon_share': 'Share',
    'share_link':'http://buddhacoin.today/{{username}}',
    'sect_greed':'Greed',
    'sect_anger':'Anger',
    'sect_obsession':'Obsession',
    'main_bid_event':'Thank you for support',
    'main_buy_event':'Thank you for purchase',
    'main_transaction_cancel':'Transaction cancelled',
    'main_explain_bonus':'When you get enough bonus, you can trade for INC',
    'main_explain_referrals':'You can get bonus when your friends purchase INC',
    'main_register_sect':'Please select your sect',
    'main_pot_intro': 'When time\'s up, pot of',
    'main_contribute': 'Contribute',
    'main_allow_approve':'Approve transaction',
    'main_allow_bid':'Bid',
    'main_processing':'Please wait',
    'main_buy_price':'1 INC = {{buy}} ETH',
    'main_sorry':'I feel sorry for that',
    'main_bidder':'goes to {{bidder}}',
    'main_pot': '{{pot}} ETH',
    'main_explain_time':'The timer increases when people bid. When the timer reaches zero, the last bidder gets the pot',
    'main_explain_price':'If you need INC, you can buy from me for {{buy}} ETH. You could also sell INC to me for {{sell}} ETH',
    'main_dialogue_image':'',
    'main_network_wrong':'MetaMask connected to wrong network',
    'main_thank': 'Thank you',
    'main_price_error': 'Unable to quote price',
    'main_game_status_error': 'Unable to know game status',
    'main_register_username':'Username',
    'main_register_cta':'May I know your name?',
    'main_register_empty_username':'',
    'main_buy_quantity':'Quantity',
    'main_buy_cta':'Buy INC to bid for the pot',
    'main_quantity_error':'How many do you want to buy?',
    'main_buy_cost':'Buy for {{cost}} ETH',
    'main_buy':'Buy',
    'main_register_success':'Welcome onboard',
    'main_congrats':'Congratulations',
    'main_not_winner':'Waiting for winner to collect',
    'main_register_refer':'Referrer',
    'main_page_title':'Mercy of Buddha',
    'main_register':'Register'

  },
  zh: {
    'lang_zh':'中',
    'lang_en':'EN',
    'lang_cn':'简',
    'head_register': '登記',
    'head_not_started': '時辰未到',
    'head_balance': '{{balance}} 壇香',
    'head_price': '{{price}} ETH',
    'head_game_ended':'燈滅',
    'head_referrals':'{{referrals}} 有緣人',
    'head_bonus':'{{bonus}} 善緣',
    'icon_eth': 'ETH',
    'icon_inc': '壇香',
    'icon_time': '剩餘時間',
    'icon_referrals':'有緣人',
    'icon_bonus':'善緣',
    'icon_share': '分享',
    'share_link':'http://buddhacoin.today/{{username}}',
    'sect_greed':'貪',
    'sect_anger':'嗔',
    'sect_obsession':'癡',
    'main_bid_event':'謝施主供奉，阿彌陀佛',
    'main_buy_event':'謝施主香油',
    'main_transaction_cancel':'施主何苦',
    // 'main_explain_bonus':'',
    'main_explain_referrals':'施主與佛有緣，陪同其他有緣人到訪，所添香油，亦是施主功德',
    'main_register_sect':'請選擇門派',
    'main_pot_intro': '燈滅剎那 觀音借庫',
    'main_contribute': '誠心上香供奉',
    'main_allow_approve':'施主請添香油',
    'main_allow_bid':'施主請上香',
    'main_processing':'施主請稍等',
    'main_buy_price':'每注壇香 {{buy}} ETH',
    'main_sorry':'請施主三思',
    'main_bidder':'予 {{bidder}}',
    'main_pot': '{{pot}} ETH',
    'main_explain_time':'殿中長明燈皆由善信香油資火，燈滅剎那觀音借庫予有緣人',
    'main_explain_price':'施主若要壇香，可向貧僧購買，每支 {{buy}} ETH；貧僧亦可回購壇香手上壇香，每支 {{sell}} ETH',
    'main_dialogue_image':'',
    'main_network_wrong':'施主，請移玉步，遠離主網',
    'main_thank': '阿彌陀佛，功德無量，福有攸歸',
    'main_price_error': '施主，有緣無份',
    'main_game_status_error': '施主，有緣無份',
    'main_register_username':'法號',
    'main_register_cta':'敢問施主尊姓大名',
    'main_register_empty_username':'',
    'main_buy_quantity':'數量',
    'main_buy_cta':'我不入佛幣，誰入佛幣？',
    'main_quantity_error':'本來無一物，何處買佛幣？',
    'main_buy_cost':'以 {{cost}} ETH 購買',
    'main_buy':'購買',
    'main_register_success':'歡迎施主光臨',
    'main_register_refer':'善緣人',
    'main_congrats':'恭喜施主',
    'main_not_winner':'請稍候贏家取庫',
    'main_page_title':'觀音借庫',
    'main_claim_cta':'施主廣結善緣，可領取壇香禮佛',
    'main_convert_rate':'{{rate}} 善緣可換 1 壇香',
    'main_claim_quantity':'領取數量',
    'main_pot_icon':'',
    'main_claim':'領取',
    'main_register':'登記'
  },
  cn:{
    'lang_zh':'中',
    'lang_en':'EN',
    'lang_cn':'简',
    'head_register': '登记',
    'head_not_started': '时辰未到',
    'head_balance': '{{balance}} 坛香',
    'head_price': '{{price}} ETH',
    'head_game_ended':'灯灭',
    'head_referrals':'{{referrals}} 有缘人',
    'head_bonus':'{{bonus}} 善缘',
    'icon_eth': 'ETH',
    'icon_inc': '坛香',
    'icon_time': '剩余时间',
    'icon_referrals':'有缘人',
    'icon_bonus':'善缘',
    'icon_share': '分享',
    'share_link':'http://buddhacoin.today/{{username}}',
    'sect_greed':'贪',
    'sect_anger':'嗔',
    'sect_obsession':'痴',
    'main_bid_event':'谢施主供奉，阿弥陀佛',
    'main_buy_event':'谢施主香油',
    'main_transaction_cancel':'施主何苦',
    'main_explain_bonus':'施主广结善缘，可换取坛香礼佛',
    'main_explain_referrals':'施主与佛有缘，陪同其他有缘人到访，所添香油，亦是施主功德',
    'main_register_sect':'请选择门派',
    'main_pot_intro': '灯灭刹那 观音借库',
    'main_contribute': '诚心上香供奉',
    'main_allow_approve':'施主请添香油',
    'main_allow_bid':'施主请上香',
    'main_processing':'施主请稍等',
    'main_buy_price':'每注坛香 {{buy}} ETH',
    'main_sorry':'请施主三思',
    'main_bidder':'予 {{bidder}}',
    'main_pot': '{{pot}} ETH',
    'main_explain_time':'殿中长明灯皆由善信香油资火，灯灭刹那观音借库予有缘人',
    'main_explain_price':'施主若要坛香，可向贫僧购买，每支 {{buy}} ETH；贫僧亦可回购坛香手上坛香，每支 {{sell}} ETH',
    'main_dialogue_image':'',
    'main_network_wrong':'施主，请移玉步，远离主网',
    'main_thank': '阿弥陀佛，功德无量，福有攸归',
    'main_price_error': '施主，有缘无份',
    'main_game_status_error': '施主，有缘无份',
    'main_register_username':'法号',
    'main_register_cta':'敢问施主尊姓大名',
    'main_register_empty_username':'',
    'main_buy_quantity':'数量',
    'main_buy_cta':'我不入佛币，谁入佛币？ ',
    'main_quantity_error':'本来无一物，何处买佛币？ ',
    'main_buy_cost':'以 {{cost}} ETH 购买',
    'main_buy':'购买',
    'main_register_success':'欢迎施主光临',
    'main_register_refer':'善缘人',
    'main_page_title':'观音借库',
    'main_register':'登记'
  }
};


i18next
  .init({
    interpolation: {
      // React already does escaping
      escapeValue: false,
    },
    lng: 'zh', // 'en' | 'es'
    // Using simple hardcoded resources for simple example
    resources: {
      en: {
        translation: lang.en,
      },
      cn:{
        translation:lang.cn,
      },
      zh: {
        translation: lang.zh,
      },
      es: {
        translation: {
          age: {label: 'Años',},
          home: {label: 'Casa',},
          name: {label: 'Nombre',},
        },
      },
    },
  });

export default i18next;
